language: node_js

node_js:
  - node

before_install:
  - sudo apt-get update
  - sudo apt-get install fakeroot jq -y
  - sudo apt-get install git-core -y
  - sudo apt-get install libavahi-compat-libdnssd-dev -y

install:
  - npm i -f

script:
  - npm run test
  - $(aws ecr get-login --no-include-email --region eu-central-1)
  - docker build -t stylifier .
  - docker tag stylifier:latest 012029284016.dkr.ecr.eu-central-1.amazonaws.com/stylifier:latest
  - docker push 012029284016.dkr.ecr.eu-central-1.amazonaws.com/stylifier:latest

env:
  global:
    - AWS_DEFAULT_REGION=eu-central-1
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - docker
      - python
      - python-pip
